export enum StatusCode {
	SUCCESS = 0,
	AUTHENTICATION_FAILURE = 1,
	BOT_NOT_FOUND = 2,
	INVALID_SESSION = 3,
	INACTIVE_SESSION = 4,
	TARGET_NOT_FOUND = 5,
	FILE_NOT_FOUND = 6,
	PERMISSION_DENIED = 10,
	MUTED = 20,
	MESSAGE_BODY_TOO_LONG = 30,
	BAD_REQUEST = 400,
}
