export enum MiraiError {
	ERR_OK = 0,
	ERR_BAD_VERIFY_KEY = 1,
	ERR_BOT_NOT_FOUND = 2,
	ERR_INVALID_SESSION = 3,
	ERR_DEACTIVATED_SESSION = 4,
	ERR_INVALID_TARGET = 5,
	ERR_FILE_NOT_FOUND = 6,
	ERR_PERMISSION_DENIED = 10,
	ERR_MUTED = 20,
	ERR_MESSAGE_TOO_LONG = 30,
	ERR_BAD_PARAMETER = 400,
}
